CLASS zrap110_travel_event_handl_030 DEFINITION
  PUBLIC
  FINAL FOR EVENTS OF zrap110_r_traveltp_030
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zrap110_travel_event_handl_030 IMPLEMENTATION.
ENDCLASS.
